name: Build and Deploy Hugo site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show git info (diagnostic)
        run: |
          git status --porcelain --branch || true
          git remote -v || true
          git rev-parse --abbrev-ref HEAD || true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.150.0'

      - name: Build
        run: hugo --minify

      - name: Show public contents (diagnostic)
        run: |
          ls -la public || true
          echo "Public size: $(du -sh public 2>/dev/null || echo '0')"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
